name: samplejavaproject_$(Date:yyyyMMdd)$(Rev:r)
trigger:
 - master
pool:
  name: Azure Pipelines
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'