name: samplejavaproject_$(Date:yyyyMMdd)$(Rev:r)
trigger:
 - master
pool:
  name: Azure Pipelines
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-java@v3
    with:
      java-version: '11'
      distribution: 'adopt'
  - name: Run the Maven verify phase
    run: mvn --batch-mode --update-snapshots verify