name: samplejavaproject_$(Date:yyyyMMdd)$(Rev:r)
trigger:
 - master
pool:
 name: pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio
steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '/p:DeployOnBuild=true  /p:WebPublishMethod=FileSystem /p:PackageAsSingleFile=true  /p:SkipInvalidConfigurations=true  /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
